name:               "DeWeese Lab"
title:              "DeWeese Lab at UC Berkeley"
description:        "this is a page for the DeWeese lab at the University of California, Berkeley"


url:                "https://deweeselab.com"
baseurl:            
permalink:          /:year/:month/:day/:title.html

markdown:           kramdown
highlighter:        rouge


nav:

  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publication"


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
    
plugins:
  - jekyll-sitemap
